### ISSUE TITLE
Spam messages detected and deleted.

### ISSUE THREAD

**Issue by bhaskarraghu** [litebitcoins/LBTC#2]
Spammer detected and deleted.

**Comment by bhaskarraghu** [comment]
![6e6b4485-1d03-434b-9aae-fa7d18dc0312](https://user-images.githubusercontent.com/33887260/34517227-33274e78-f0a0-11e7-9c98-5f9e3ab4a691.jpg)

**Comment by litebitcoins** [comment]
Do not waste our time as well as your time posting senseless messages. try to learn how mining works.

You can not relate LBTC community members or any Modetarotor who monitor group chat to keep safe from spam with Core development team.
