### ISSUE TITLE
dont wast our time first before creating a coin learn manner and how to speak with others 

### ISSUE THREAD

**Issue by bhaskarraghu** [litebitcoins/LBTC#3]
stupid team first try to give respect to users or investers on your coin or company did your mother teached you like this ? what you have learned from school ? blaming with unnecessary things even ur team dont have any mannner how to speak with people and dont know where these all people are came from first dont wast our time first

**Comment by bhaskarraghu** [comment]
if your team didnt do any thing wrong why my old post was reported to spam and removed ? and also removed from issues path . its showes the reality how cheap persons maintaing the coins very worest service . without providing info when a issue was come simple banning us and making as spam and removing us is it resolvituon ? first learl how to speak with others then create a coin or do a job dont wast our time 
![kavya-madhavan-ittechstuff 8](https://user-images.githubusercontent.com/33887260/42488486-6be2bf56-8423-11e8-872f-a228291cc059.jpg)

**Comment by litebitcoins** [comment]
Spam
