### ISSUE TITLE
first your team learn manus how to speak with investers 

### ISSUE THREAD

**Issue by bhaskarraghu** [litebitcoins/LBTC#4]
after posting a complaint its title changed to spammer and removed the post . what a resolvition ? i just asking one question from started i have mined almost 2 days so where can i find how much coines i earned and log of my work to check ? this a spam message for your company ? first learn how to answer then start a company no proper support support and using volger language on us in group chat and maked me spam overall wasting time on LTBC every one fake support . if we ask a question your tech team wont replay report us as spam and blame us without proper way to speak ... i dont know how there mother teached them manus to speak with others even in schools what did they learned wand his father too ...

**Comment by litebitcoins** [comment]
deer user, this is not isssue spam reported and closed
it's not support where you can ask how mine "with my old notebook" use google or official tegeram chanel.
